[casmarts_nodes]
10.4.3.23 ansible_user=casmartbd ansible_ssh_private_key_file=/app/keys/casmart.key ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
10.4.3.208 ansible_user=authentik ansible_ssh_private_key_file=/app/keys/casmarts.key ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
10.4.3.30 ansible_user=kiwi ansible_ssh_private_key_file=/app/keys/casmarts.key ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
10.4.3.31 ansible_user=chatbotpdf ansible_ssh_private_key_file=/app/keys/casmarts.key ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
10.4.3.25 ansible_user=casmartsuperset ansible_ssh_private_key_file=/app/keys/casmarts.key ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
