import os
import sys
import json
import hashlib
import subprocess
from datetime import datetime
from core import db_manager

def log_vulnerability(asset_id, cve_id, severity, description):
    """Logs the vulnerability in vulnerability_log database table."""
    try:
        from core import deduplication_engine
        with db_manager.get_db_cursor() as cur:
            # cve_id here already encodes file+line via a stable hash suffix (see
            # run_medusa_scan below), so it's already a unique, stable per-finding identifier --
            # passed as url_path to keep the fingerprint keyed the same way the original
            # (asset_id, cve_id) dedup was, just with fingerprint_hash/MITRE mapping added.
            action, _ = deduplication_engine.log_finding_deduplicated(
                cur, asset_id, cve_id, severity, description, "medusa",
                url_path=cve_id, open_status="NEW", preserve_status=True
            )
            if action == "updated":
                print(f"  🔄 Updated Medusa finding in DB: [{severity}] {cve_id}")
            elif action == "merged":
                print(f"  🔗 Merged Medusa finding into existing cross-tool ticket: [{severity}] {cve_id}")
            else:
                print(f"  📝 Logged Medusa finding in DB: [{severity}] {cve_id}")
    except Exception as e:
        print(f"❌ [Auditor-Medusa] Error logging to DB: {e}")

def run_medusa_scan(repo_path, asset_id):
    """
    Executes medusa scan on target repository and parses the JSON output.
    Stores findings inside Postgres vulnerability_log.
    """
    print(f"🎯 [Auditor-Medusa] Starting Medusa AI SAST Scan on: {repo_path} (Asset ID: {asset_id})")
    
    if not os.path.exists(repo_path):
        print(f"⚠️ [Auditor-Medusa] Path {repo_path} does not exist. Skipping.")
        return False

    # Create a temporary directory inside the app's own data folder
    output_dir = os.path.join("/app/data/medusa_runs", str(asset_id))
    os.makedirs(output_dir, exist_ok=True)
    
    # Define report path
    report_file = os.path.join(output_dir, "medusa-report.json")
    if os.path.exists(report_file):
        try:
            os.remove(report_file)
        except: pass

    # No special flag needed at all: with no TTY attached (always true under subprocess.run,
    # which is how this is invoked), medusa-security 2026.7.0 auto-detects it can't prompt and
    # prints "Non-interactive mode: continuing without optional tools." on its own. Verified via
    # a real scan. Neither the old `echo "yes" | ... --no-ai-safe` (a flag that, confusingly,
    # DOES exist in this exact pinned version but does something unrelated — disabling payload
    # obfuscation, not confirming prompts) nor `--no-install` (which doesn't exist in this
    # version at all — it belonged to a different/newer resolve seen during ad-hoc testing
    # before requirements.txt pinned the version) were ever the right fix.
    # -w 1 forces a single worker (no multiprocessing pool). With the default auto-detected
    # worker count (>1), every real test run crashed with a BrokenPipeError inside Python's
    # multiprocessing.Pool while sending a result back to the parent — reproduced consistently
    # regardless of host load (confirmed both under heavy contention and on an idle host), so
    # it's a genuine bug in this version's worker-pool IPC, not resource starvation. With -w 1
    # the same repo scanned cleanly in ~9s with a real report and no crash.
    cmd = f'medusa scan "{repo_path}" --format json -o "{output_dir}" -w 1'
    
    print(f"🚀 Running: {cmd}")
    try:
        # 300s wasn't enough for a real run in testing — Medusa shells out to other scanners
        # (observed spawning `trivy fs --scanners vuln,secret,misconfig` as a sub-process, which
        # downloads/refreshes its CVE database on a cold cache) on top of its own ~45 analyzers.
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=900)
        
        # Look for the generated json report in the output folder. Medusa 2026.7.0 always
        # writes a second, unrelated "scan_history.json" (a list, not a report dict) alongside
        # the real report, and the real report's own filename is timestamped
        # ("medusa-scan-YYYYMMDD-HHMMSS.json"), not a fixed "medusa-report.json"/"report.json"
        # as originally assumed — picking the first *.json file by directory-listing order
        # non-deterministically grabbed scan_history.json and crashed on `data.get(...)`.
        found_report = None

        # Check files inside output_dir
        files_in_dir = os.listdir(output_dir)
        print(f"📁 Files generated by Medusa: {files_in_dir}")

        for fname in files_in_dir:
            if fname.endswith(".json") and fname != "scan_history.json":
                found_report = os.path.join(output_dir, fname)
                break
                
        if not found_report or not os.path.exists(found_report):
            print(f"⚠️ [Auditor-Medusa] No JSON report found in {output_dir}.")
            print(f"Stdout: {result.stdout[:1000]}")
            print(f"Stderr: {result.stderr[:1000]}")
            return False
            
        # Parse the JSON report
        with open(found_report, "r") as f:
            data = json.load(f)
            
        findings = data.get("findings", [])
        if not findings and "results" in data:
            findings = data.get("results", [])
            
        print(f"✨ Medusa found {len(findings)} potential issues.")
        
        logged_count = 0
        for item in findings:
            # Map Medusa fields to DB columns
            rule_id = item.get("rule_id", "MEDUSA-GENERIC-AI-FINDING")
            severity = item.get("severity", "Medium").upper()
            
            # Severity translation
            if severity not in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
                severity = "MEDIUM"
                
            file_path = item.get("file_path", "unknown")
            line = item.get("line_number", item.get("line", 0))
            description = item.get("description", "No description provided.")
            code_snippet = item.get("snippet", item.get("code", ""))
            
            detailed_desc = (
                f"**Vulnerabilidad detectada por Medusa Security**\n\n"
                f"**Regla:** `{rule_id}`\n"
                f"**Descripción:** {description}\n"
                f"**Archivo:** `{file_path}` (Línea {line})\n"
            )
            if code_snippet:
                detailed_desc += f"\n**Código Afectado:**\n```python\n{code_snippet}\n```"
                
            # Use unique identifier for CVE to prevent duplicate spamming. Must be a stable hash
            # across process restarts — Python's built-in hash() randomizes string hashing per
            # process (PYTHONHASHSEED) by default, so the old `hash(...)` call produced a
            # different cve_id for the exact same finding every time the container restarted,
            # silently defeating log_vulnerability()'s dedupe-by-(asset_id, cve_id) check and
            # re-inserting every finding as "new" on every restart (the same failure mode as the
            # PROWLER-AUDIT duplicate-flooding bug, via a different root cause). hashlib is
            # deterministic across runs. Medusa's own rule_id is already "MEDUSA-"-prefixed, so
            # strip it here to avoid a doubled "MEDUSA-MEDUSA-..." prefix.
            short_rule_id = rule_id[len("MEDUSA-"):] if rule_id.upper().startswith("MEDUSA-") else rule_id
            stable_hash = hashlib.sha256(f"{file_path}:{line}".encode()).hexdigest()[:8]
            cve_id = f"MEDUSA-{short_rule_id}-{stable_hash}"
            
            log_vulnerability(asset_id, cve_id, severity, detailed_desc)
            logged_count += 1
            
        print(f"✅ Medusa scan integration complete. Logged {logged_count} findings.")
        return True
        
    except subprocess.TimeoutExpired:
        print("❌ [Auditor-Medusa] Medusa scan timed out.")
        return False
    except Exception as e:
        print(f"❌ [Auditor-Medusa] Unexpected error during scan: {e}")
        return False

def run(asset_id: int, repo_path: str = ""):
    """Wrapper function for auditor_ext compatibility."""
    return run_medusa_scan(repo_path, asset_id)

if __name__ == "__main__":
    # Test scan if run directly
    if len(sys.argv) > 2:
        run_medusa_scan(sys.argv[1], int(sys.argv[2]))
    else:
        print("Usage: python auditor_medusa.py <repo_path> <asset_id>")
