import os
import sys
import json
import subprocess
from datetime import datetime
from core import db_manager

def log_vulnerability(asset_id, cve_id, severity, description):
    """Logs the vulnerability in vulnerability_log database table."""
    try:
        with db_manager.get_db_cursor() as cur:
            # Check if this vulnerability already exists for this asset and CVE
            cur.execute("""
                SELECT id FROM vulnerability_log 
                WHERE asset_id = %s AND cve_id = %s
            """, (asset_id, cve_id))
            exists = cur.fetchone()
            
            if exists:
                # Update it
                cur.execute("""
                    UPDATE vulnerability_log 
                    SET severity = %s, description = %s, detected_at = NOW()
                    WHERE id = %s
                """, (severity, description, exists[0]))
                print(f"  🔄 Updated Medusa finding in DB: [{severity}] {cve_id}")
            else:
                # Insert it
                cur.execute("""
                    INSERT INTO vulnerability_log (asset_id, cve_id, severity, description, status, detected_at)
                    VALUES (%s, %s, %s, %s, 'NEW', NOW())
                """, (asset_id, cve_id, severity, description))
                print(f"  📝 Logged Medusa finding in DB: [{severity}] {cve_id}")
    except Exception as e:
        print(f"❌ [Auditor-Medusa] Error logging to DB: {e}")

def run_medusa_scan(repo_path, asset_id):
    """
    Executes medusa scan on target repository and parses the JSON output.
    Stores findings inside Postgres vulnerability_log.
    """
    print(f"🎯 [Auditor-Medusa] Starting Medusa AI SAST Scan on: {repo_path} (Asset ID: {asset_id})")
    
    if not os.path.exists(repo_path):
        print(f"⚠️ [Auditor-Medusa] Path {repo_path} does not exist. Skipping.")
        return False

    # Create a temporary directory inside the app's own data folder
    output_dir = os.path.join("/app/data/medusa_runs", str(asset_id))
    os.makedirs(output_dir, exist_ok=True)
    
    # Define report path
    report_file = os.path.join(output_dir, "medusa-report.json")
    if os.path.exists(report_file):
        try:
            os.remove(report_file)
        except: pass

    # Execute Medusa scan command non-interactively by piping 'yes'
    cmd = f'echo "yes" | medusa scan "{repo_path}" --format json -o "{output_dir}" --no-ai-safe'
    
    print(f"🚀 Running: {cmd}")
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=300)
        
        # Look for the generated json report in the output folder
        # Medusa usually generates a json report named report.json or medusa-report.json
        possible_names = ["medusa-report.json", "report.json"]
        found_report = None
        
        # Check files inside output_dir
        files_in_dir = os.listdir(output_dir)
        print(f"📁 Files generated by Medusa: {files_in_dir}")
        
        for fname in files_in_dir:
            if fname.endswith(".json"):
                found_report = os.path.join(output_dir, fname)
                break
                
        if not found_report or not os.path.exists(found_report):
            print(f"⚠️ [Auditor-Medusa] No JSON report found in {output_dir}.")
            print(f"Stdout: {result.stdout[:1000]}")
            print(f"Stderr: {result.stderr[:1000]}")
            return False
            
        # Parse the JSON report
        with open(found_report, "r") as f:
            data = json.load(f)
            
        findings = data.get("findings", [])
        if not findings and "results" in data:
            findings = data.get("results", [])
            
        print(f"✨ Medusa found {len(findings)} potential issues.")
        
        logged_count = 0
        for item in findings:
            # Map Medusa fields to DB columns
            rule_id = item.get("rule_id", "MEDUSA-GENERIC-AI-FINDING")
            severity = item.get("severity", "Medium").upper()
            
            # Severity translation
            if severity not in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
                severity = "MEDIUM"
                
            file_path = item.get("file_path", "unknown")
            line = item.get("line_number", item.get("line", 0))
            description = item.get("description", "No description provided.")
            code_snippet = item.get("snippet", item.get("code", ""))
            
            detailed_desc = (
                f"**Vulnerabilidad detectada por Medusa Security**\n\n"
                f"**Regla:** `{rule_id}`\n"
                f"**Descripción:** {description}\n"
                f"**Archivo:** `{file_path}` (Línea {line})\n"
            )
            if code_snippet:
                detailed_desc += f"\n**Código Afectado:**\n```python\n{code_snippet}\n```"
                
            # Use unique identifier for CVE to prevent duplicate spamming
            cve_id = f"MEDUSA-{rule_id}-{hash(file_path + str(line)) & 0xffffffff:x}"
            
            log_vulnerability(asset_id, cve_id, severity, detailed_desc)
            logged_count += 1
            
        print(f"✅ Medusa scan integration complete. Logged {logged_count} findings.")
        return True
        
    except subprocess.TimeoutExpired:
        print("❌ [Auditor-Medusa] Medusa scan timed out.")
        return False
    except Exception as e:
        print(f"❌ [Auditor-Medusa] Unexpected error during scan: {e}")
        return False

if __name__ == "__main__":
    # Test scan if run directly
    if len(sys.argv) > 2:
        run_medusa_scan(sys.argv[1], int(sys.argv[2]))
    else:
        print("Usage: python auditor_medusa.py <repo_path> <asset_id>")
